### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by cats256** [Afek-Sakaju/digital-clock-react#1]
I had to do npm install sass --save-dev and npm install @babel/plugin-proposal-private-property-in-object --save-dev to actually get it to work

**Comment by Afek-Sakaju** [comment]
> I had to do npm install sass --save-dev and npm install @babel/plugin-proposal-private-property-in-object --save-dev to actually get it to work

Sorry for the late response, haven't been here for a while since mostly using my company's account, will make sure the problem will be fixed

Thank you for your feedback! @cats256

**Comment by Afek-Sakaju** [comment]
Fixed, and added additional packages improvements such as moving react and react-dom to the peerDeps
update 1.2.0^ includes the fixed version
@cats256 
@hdriel

**Comment by cats256** [comment]
Nice!
